services:

    cts_kaps.Scraping:
        class: CTS\KapsBundle\Services\Scraping
        arguments: ["@doctrine.orm.entity_manager"]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
        - { name: twig.extension }