services:

    cts_kaps.Scraping:
        class: CTS\KapsBundle\Services\Scraping
        arguments: ["@doctrine.orm.entity_manager", "@cts_kaps.Formatting"]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
        - { name: twig.extension }

    cts_kaps.Paginator:
        class: CTS\KapsBundle\Services\Paginator
        arguments: ["@doctrine.orm.entity_manager"]

    cts_kaps.Formatting:
        class: CTS\KapsBundle\Services\Formatting

    cts_kaps.SendEmail:
        class: CTS\KapsBundle\Services\SendEmail
        arguments: ["@mailer", "@templating"]

    cts_kaps.ResetPassword:
        class: CTS\KapsBundle\Services\ResetPAssword
        arguments: ["@cts_kaps.sendEmail"]