<?php

namespace CTS\KapsBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArticleWith($data)
    {
        $queryBuilder=$this->createQueryBuilder('a');
        $queryBuilder
            ->select('a.title', 'a.excerpt')
            ->where ('a.title= :key')
            ->orWhere('a.excerpt= :key')
            ->orderBy('a.title', 'ASC')
            ->setParameter('key', '%'.$data.'%');
        return $queryBuilder->getQuery()->getResult();
    }
}
