<?php

namespace CTS\KapsBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast()
    {
        $queryBuilder=$this->createQueryBuilder('m');
        $queryBuilder
            ->orderBy('m.createdAt', 'DESC')
            ->setMaxResults(3);
            return $queryBuilder->getQuery()->getResult();
    }

}
