<?php

namespace CTS\KapsBundle\Repository;

/**
 * SelectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectorRepository extends \Doctrine\ORM\EntityRepository
{
}
