<?php

namespace CTS\KapsBundle\Repository;

/**
 * USerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class USerRepository extends \Doctrine\ORM\EntityRepository
{
}
